version: '3.4'

services:
  beter.feed.testingsandbox.generator:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - FeedEmulator__ApiBaseUrl=http://beter.feed.testing-sandbox.emulator
      - Publisher__BootstrapServers=kafka:29092
      - Publisher__Topic=feed-testing-sandbox-generator
      - Publisher__SecurityProtocol=0
      - Publisher__AllowAutoCreateTopics=true
      - Heartbeat__IntervalInSeconds=5
    ports:
       - 51857:80
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro 

  beter.feed.testingsandbox.emulator:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80,
      - Messaging__ConsumerConfig__BootstrapServers=kafka:29092
      - Messaging__ConsumerConfig__SecurityProtocol=0
      - Messaging__ConsumerConfig__AutoOffsetReset=Earliest
      - Messaging__ConsumerConfig__GroupId=feed-emulator:test
      - Messaging__Topics__TestingTools=feed-testing-sandbox-generator
      - SignalR__FeedTimeTableEndpoint=/time_table
      - SignalR__FeedTradingEndpoint=/trading
      - SignalR__FeedScoreboardEndpoint=/scoreboard
      - SignalR__FeedIncidentEndpoint=/incident
    ports:
       - 51858:80
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro 